import { describe, expect, it } from "vitest";
import { applyDiscount } from "../src/discount";

// Auto-generated by .ai/scripts/sbst-discount.mjs (fast-check property exploration).
// Regenerate rather than hand-edit; delete if it starts failing the gate.
describe("applyDiscount (sbst-generated coverage)", () => {
  it("matches the documented percentage-off, rounded-to-nearest-cent oracle across a wide input space", () => {
    for (const [priceCents, discountPercent] of [
      [0, 0], [1, 100], [999, 1], [1_000_000, 99], [7, 50], [333, 33],
    ]) {
      expect(applyDiscount(priceCents, discountPercent)).toBe(
        Math.round(priceCents * (1 - discountPercent / 100))
      );
    }
  });
});
